---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    #- verify
    - destroy

platforms:
  - name: apps-graylog-exporter-${MOLECULE_DISTRIB:-debian11}
    image: lotusnoir/ansible_molecule_test_images:${MOLECULE_DISTRIB:-debian11}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml

verifier:
  name: ansible
