---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: debian11
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - cleanup
    - destroy

platforms:
  - name: apps-graylog-exporter-debian11
    image: lotusnoir/ansible_molecule_test_images:debian11
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  connection_options:
    ansible_remote_tmp: /tmp
    ansible_python_interpreter: auto_silent
  config_options:
    defaults:
      roles_path: "${HOME}/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:$MOLECULE_PROJECT_DIRECTORY/.."
      callbacks_enabled: timer, profile_tasks, profile_roles
      verbosity: 3
      forks: 20
      host_key_checking: false
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
  log: true
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml

verifier:
  name: ansible
